### ISSUE TITLE
No error handling

### ISSUE THREAD

**Issue by ankeshp03** [ankeshp03/finalProject#2]
JQuery error is shown in the console when there are any PHP errors.
Internal Server Error.

**Comment by dev-sanjay** [comment]
Yes I cant login the Faculty members on a localhost

**Comment by ankeshp03** [comment]
In the faculty database, admin, head proctor, proctor and other facilities
come. Please mention which member you were trying to log in.
Also the faculty module is not done yet, that is, the normal faculties do
not have any dashboard yet, but admin, head proctor and proctor should be
able to login.
Please let me know if any problem arises.

**Comment by dev-sanjay** [comment]
Still cant login the admin "Internal Server Error" localhost

what are the others login credentials for faculty members?

**Comment by ankeshp03** [comment]
Login credentials for
Admin: admin@acharya.ac in
Password: admin123

Head Proctor: headp@acharya.ac.in
Password: ait123

Proctor: yatheesh@acharya.ac.in
Password: ait456

Faculty: kalavenugopal@acharya.ac.in
Password: ait789

**Comment by ankeshp03** [comment]
Please take the updated database from
https://github.com/ankeshp03/finalProject/tree/master/db

And also take the updated code, since I have made some changes in few of
the files.

Do let me know if any issues occur.

**Comment by Karla02** [comment]
Thank you so much!!!!

**Comment by ankeshp03** [comment]
Is it working?

**Comment by dev-sanjay** [comment]
Guys can you tell me why am I getting this messages while I am not posting
anything ?

**Comment by ankeshp03** [comment]
You have subscribed to the notification maybe that's why, you can unsubscribe it.
